name: Terraform AWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual run

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      # To destroy manually, run workflow_dispatch and comment above apply, uncomment below:

      # - name: Terraform Destroy
      #   if: github.event_name == 'workflow_dispatch'
      #   run: terraform destroy -auto-approve

    # Configure AWS credentials
    # We'll set environment variables from secrets to authenticate AWS CLI/SDK used by Terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
